services:
    FamilyWebDiffusion\SyliusKlarnaPaymentsPlugin\EventListener\PaymentFailedEventListener:
        public: true
        tags:
            - { name: 'doctrine.orm.entity_listener', entity: 'Sylius\Component\Core\Model\Payment', event: 'postUpdate', method: 'cancelExistingKlarnaAuthorizationToken' }
        arguments:
            - '@FamilyWebDiffusion\SyliusKlarnaPaymentsPlugin\Payum\KlarnaPaymentsApiClient'
